SODEV-33350 - feat: needs-one-more label
buildcom/the-sorting-hat pull request #12
Opened 2022-01-18 17:44 UTC by lisadean

2022-01-18 17:49 UTC, broffis approved these changes

2022-01-19 18:37 UTC, radfahrer requested changes

2022-01-19 18:37 UTC, radfahrer commented on src/pullRequestReviewEvent.ts
> +			}
I'm wondering if this will actually miss the use-case where a first review is approved.

2022-01-19 18:53 UTC, lisadean commented on src/pullRequestReviewEvent.ts
> +			}
Yeah, that's better. And, in fact, I'm going to remove the `label.find` to make it even cleaner. Because it's checking the label of the PR at the point it was passed into the workflow. There's is a tiny chance it could change and these rest calls are super quick anyway.

Either logic flow should catch a first approving review though. Because `reviewDecision` is never going to be 'APPROVED' with only one review, so it will always add the label.

2022-01-19 18:56 UTC, radfahrer approved these changes

2022-01-20 15:57 UTC, broffis approved these changes

2022-01-20 15:57 UTC, merged